campus/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
urlpatterns = [
    path('student/student_register/' , views.student_register , name='student_register'),
    path('student/student_login/', views.student_login,name='student_login'),
    path('student/student_login/usd/',views.usd,name='usd'),
    path('logout/', views.pagelogout, name='logout'),
    path('student/student_login/dispstu/',views.dispstu,name='dispstu'),
    path('company/company_register/', views.company_register, name='company_register'),
    path('company/company_login/', views.company_login, name='company_login'),
    path('company/company_login/ccd/', views.ccd, name='ccd'),
    path('company/company_login/jp/', views.jobpos, name='jp'),
    path('company/company_login/jd/', views.jd, name='jd'),
    path('company/company_login/deletevacan/', views.deletevacan, name='deletevacn'),
    path('company/company_login/viewpos/', views.viewpos, name='viewpos'),
    path('student/student_login/applyjob/', views.applyjob, name='apply'),
    path('student/student_login/applyjob/<str:opt>/', views.apply, name='apply1'),
    path('', views.home, name='home'),
    path('company/company_login/selectstu/', views.selectstu, name='sstu'),
    path('company/company_login/selectstu/<str:opt>/',views.stumail,name="sm")
    

]

crs/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls,name='admin'),
    path('', include('campus.urls')),
    path('student/student_register/', include('campus.urls')),
    path('student/student_login/',include('campus.urls')),
    path('student/student_login/usd/',include('campus.urls')),
    path('logout/',include('campus.urls')),
    path('student/student_login/dispstu/', include('campus.urls')),
    path('company/company_register/', include('campus.urls')),
    path('company/company_login/', include('campus.urls')),
    path('company/company_login/ccd/',include('campus.urls')),
    path('company/company_login/jp/', include('campus.urls')),
    path('company/company_login/jd/', include('campus.urls')),
    path('company/company_login/viewpos/', include('campus.urls')),
    path('student/student_login/applyjob/',include('campus.urls')),
    path('student/student_login/applyjob/<str:opt>/',include('campus.urls')),
    path('company/company_login/selectstu/', include('campus.urls')),
    path('company/company_login/selectstu/<str:opt>/',include('campus.urls')),

]

campus/models.py
from django.core.validators import MaxValueValidator,MinValueValidator,MaxLengthValidator,MinLengthValidator
from django.db import models
from django.contrib.auth.models import  AbstractUser
from django.contrib.auth.models import User

done = (
    ('yes', 'yes'),
    ('no', 'no'),
)


class stu_details(models.Model):
    branch_choices = (
        ('it', 'information_technology'),
        ('me', 'mech'),
        ('ce', 'civil'),
        ('eee', 'eee'),
        ('ece', 'ece'),
        ('ch', 'chemical'),
        ('cse', 'cse'),
    )
    gender = (
        ('male', 'male'),
        ('female', 'female'),
        ('others','others'))

    username=models.CharField(max_length=9,blank=False,help_text="enter username ex:y16it***",default="y1")
    name = models.CharField(max_length=30, blank=False, help_text='*required',default="full name")
    phone_number = models.CharField(validators=[MaxLengthValidator(10),MinLengthValidator(10)] ,help_text='*required',max_length=10)
    fathers_name = models.CharField(max_length=30, blank=False, help_text='*required')
    mothers_name = models.CharField(max_length=30, blank=False, help_text='*required')
    gender=models.CharField(blank=False, choices=gender,max_length=10)
    place = models.CharField(max_length=30, blank=False)
    branch = models.CharField(blank=False, choices=branch_choices, max_length=10)
    cgpa_Btech = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
    class_10_cgpa = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(10)],blank=False,help_text='*required')
    class_12_percentage = models.FloatField(validators=[MinValueValidator(0),MaxValueValidator(100)],blank=False,help_text='*required')
    certifications_count = models.IntegerField(blank=False)
    internship = models.CharField(blank=False, choices=done,max_length=10)
    languages = models.CharField(max_length=100, blank=False, help_text='*required')
    sop = models.CharField(max_length=500, default="statement of purpose", help_text='*required')
    dob = models.DateField(blank=False, help_text='*format is YYYY-MM-DD', )
    email = models.EmailField(max_length=254, blank=False, help_text='Required. Inform a valid email address.',default="anudeep.insvirat@gmail.com")

    def __str__(self):
       return self.username


class comp_details(models.Model):
    username=models.CharField(max_length=30,blank=False , help_text='*required')
    company_name = models.CharField(max_length=30, blank=False, help_text='*required')
    est_year = models.CharField(max_length=4, blank=False, help_text="*required")
    hr_name = models.CharField(max_length=30, blank=False, help_text='*required')
    hr_phn = models.CharField(max_length=10,validators=[MinValueValidator(10),MaxValueValidator(10)], blank=False, help_text='*required')
    headquaters = models.CharField(max_length=30,blank=False, help_text='*required')
    about = models.CharField(max_length=1000, blank=False, help_text='*required')
    type = models.CharField(max_length=100, blank=False)
    email = models.EmailField(max_length=254,blank=False, help_text='Required. Inform a valid email address.')

    def __str__(self):
        return self.username

class job_pos(models.Model):
    job_id=models.CharField(max_length=30, blank=False, help_text='*required',unique=True)
    username = models.CharField(max_length=30, blank=False, help_text='*required')
    company_name = models.CharField(max_length=30, blank=False, help_text='*required')
    designation = models.CharField(max_length=30, blank=False, help_text='*required')
    salary=models.IntegerField( blank=False, help_text='*required')
    bond_years=models.IntegerField( blank=False, help_text='*required')
    information_technology= models.CharField(blank=False, choices=done, max_length=10)
    mech= models.CharField(blank=False, choices=done, max_length=10)
    civil= models.CharField(blank=False, choices=done, max_length=10)
    eee = models.CharField(blank=False, choices=done, max_length=10)
    ece= models.CharField(blank=False, choices=done, max_length=10)
    chemical= models.CharField(blank=False, choices=done, max_length=10)
    cse= models.CharField(blank=False, choices=done, max_length=10)

    def __str__(self):
        return self.job_id


class applied_jobs(models.Model):
    company_id = models.CharField(max_length=30, blank=False, help_text='*required' ,default="company id")
    job_id = models.CharField(max_length=30, blank=False, help_text='*required',default="job id")
    student_id= models.CharField(max_length=9, blank=False, help_text="enter username ex:y16it***", default="y1")

    def __str__(self):
        return self.job_id

campus/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import Student_SignUpForm,UsdForm,dispstuForm,company_SignUpForm,ccdForm,jobposForm
from django.contrib.auth.models import Group
from django.contrib.auth import authenticate
from django.http import HttpResponse
from django.views.generic.edit import CreateView
from campus.models import stu_details,comp_details,job_pos,applied_jobs
from django.core.mail import EmailMessage
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic import TemplateView
from django.utils.decorators import method_decorator

# Create your views here
def  student_login(request):
    if request.user.is_authenticated and request.user.groups.filter(name='student').exists():
        return render(request,'campus/stulog.html')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if request.user.groups.filter(name='student').exists():
             return render(request, 'campus/stulog.html', {'form': form})
            else:
                logout(request)
                return render(request, 'campus/student_login.html', {'form': form})
        else:
            return render(request, 'campus/student_login.html', {'form': form})


    else:
        form = AuthenticationForm()
        return render(request, 'campus/student_login.html', {'form': form})

def  home(request):
    return render(request,'campus/home.html')

def pagelogout(request):
        logout(request)

        return redirect('http://127.0.0.1:8000/')


def student_register(request):
    if request.method == 'POST':
        form = Student_SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            group = Group.objects.get(name='student')
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('http://127.0.0.1:8000/student/student_login/')

        else:
            return render(request, 'campus/register.html', {'form': form})
    else:
        form =Student_SignUpForm()
        return render(request, 'campus/register.html', {'form': form})

#@login_required
#@user_passes_test(lambda u: u.groups.filter(name='Student').count() == 1)
def usd(request):
 if  request.user.is_authenticated and request.user.groups.filter(name='student').exists():
    if request.method == "POST":
            form=UsdForm(request.POST)
            if form.is_valid():
                stu = request.user.username
                post = stu_details.objects.filter(username=stu)
                x= request.POST.get('sop')
                y=request.POST.get('phone_number')
                db=request.POST.get('dob')
                e=request.POST.get('email')
                l=request.POST.get('languages') 
                cc=request.POST.get('certifications_count')
                i=request.POST.get('internship')
                c12=request.POST.get('class_12_percentage')
                c10=request.POST.get('class_10_cgpa')
                b=request.POST.get('branch')
                cb=request.POST.get('cgpa_Btech')
                p=request.POST.get('place')
                g=request.POST.get('gender')
                fn=request.POST.get('fathers_name')
                mn=request.POST.get('mothers_name')
                name=request.POST.get('name')

                j=post[0]
                j.sop =x
                j.phone_number = y
                j.dob=db
                j.email=e
                j.languages=l
                j.certifications_count=cc
                j.internship=i
                j.class_12_percentage=c12
                j.class_10_cgpa=c10
                j.branch=b
                j.cgpa_Btech=cb
                j.place=p
                j.gender=g
                j.fathers_name=fn
                j.mothers_name=mn
                j.name=name
                j.save()
                return render(request, 'campus/stulog.html')

    else:
        stu = request.user.username
        post = stu_details.objects.filter(username=stu)
        x = post[0].sop
        x=str(x)
        y = post[0].phone_number
        print(x,y,post)
        form=UsdForm()
        db=post[0].dob
        e=post[0].email
        l=post[0].languages 
        cc=post[0].certifications_count
        i=post[0].internship
        c12=post[0].class_12_percentage
        c10=post[0].class_10_cgpa
        b=post[0].branch
        cb=post[0].cgpa_Btech
        p=post[0].place
        g=post[0].gender
        fn=post[0].fathers_name
        mn=post[0].mothers_name
        name=post[0].name
        context={'form': form,'x':x,'y':y,'db': db,"e":e,"l":l,"cc":cc,"i":i,"c12":c12,"c10":c10,"b":b,"cb":cb,"p":p,"g":g,"fn":fn,"mn":mn,"name":name}
        return render(request, 'campus/usd.html',context)
 else:
     return HttpResponse("<h1>u r not logged in</h1>")



def dispstu(request):
    if request.user.is_authenticated and request.user.groups.filter(name='student').exists():
        stu = request.user.username
        post = stu_details.objects.filter(username=stu)
        form=dispstuForm()
        return render(request, 'campus/dispstu.html', {'form': form, 'post': post})
    else:
        return HttpResponse("<h1>u r not logged in</h1>")



def company_register(request):
    if request.method == 'POST':
        form = company_SignUpForm(request.POST)
        if form.is_valid():
            user=form.save()
            group = Group.objects.get(name='company')
            user.groups.add(group)
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            a=comp_details()
            a.username=request.POST.get('username')
            a.company_name=request.POST.get('company_name')
            a.email=request.POST.get('email')
            a.est_year=request.POST.get('est_year')
            a.type=request.POST.get('type')
            a.about=request.POST.get('about')
            a.hr_name=request.POST.get('hr_name')
            a.hr_phn=request.POST.get('hr_phn')
            a.headquaters=request.POST.get('headquaters')
            a.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('http://127.0.0.1:8000/')
        else:
            return render(request, 'campus/register1.html', {'form': form})

    else:
        form =company_SignUpForm()
        return render(request, 'campus/register1.html', {'form': form})



def  company_login(request):
    if request.user.is_authenticated and request.user.groups.filter(name='company').exists():
        return render(request,'campus/comlog.html')
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if request.user.groups.filter(name='company').exists():
             return render(request, 'campus/comlog.html', {'form': form})
            else:
                logout(request)
                return render(request, 'campus/company_login.html', {'form': form})
        else:
            return render(request, 'campus/company_login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request, 'campus/company_login.html', {'form': form})




def ccd(request):
 if  request.user.is_authenticated and request.user.groups.filter(name='company').exists():
    if request.method == "POST":
            form=ccdForm(request.POST)
            if form.is_valid():
                stu = request.user.username
                post = comp_details.objects.filter(username=stu)
                x= request.POST.get('hr_name')
                y=request.POST.get('hr_phn')
                z=request.POST.get('about')
                j=post[0]
                j.hr_name =x
                j.hr_phn = y
                j.about=z
                j.save()
                return render(request, 'campus/comlog.html')

    else:
        stu = request.user.username
        post = comp_details.objects.filter(username=stu)
        x = post[0].hr_name
        x=str(x)
        y = post[0].hr_phn
        z=post[0].about
        form=ccdForm()
        return render(request, 'campus/ccd.html', {'form': form,'x':x,'y':y,'z':z})
 else:
     return HttpResponse("<h1>u r not logged in</h1>")



def jobpos(request):
    if request.user.is_authenticated and request.user.groups.filter(name='company').exists():
        if request.method == "POST":
            form = jobposForm(request.POST)
            if form.is_valid():
                    model_instance = form.save(commit=False)
                    model_instance.save()
                    return render(request,'campus/comlog.html')
            else:
                return render(request, 'campus/jobpos.html', {'form': form})
        else:
            form = jobposForm()
            x = request.user.username
            y = comp_details.objects.filter(username=x)
            y = str(y[0].company_name)
            y=y.split()
            y1=""
            for i in y:
                y1=y1+"_"+i
            y1=y1[1:len(y1)]
            print(y)

            return render(request, 'campus/jobpos.html', {'form': form,'x':x,'y':y1})
    else:
        return HttpResponse("<h1>u r not logged in</h1>")

def jd(request):
    if request.user.is_authenticated and request.user.groups.filter(name='company').exists():

campus/templates/campus/applyjob.html
{% extends "campus/base.html" %}

{% block body_block %}

      <div class="container">
        <div class="row">
          <div class="col-md-6 mx-auto text-center mb-5 section-heading">
          
            <br>
            <h2> APPLY FOR JOB!</h2>
          </div>
        </div>
      </div>
</div>
<div class="container">

  <div class="jumbotron">
      <h1>{{ s }}</h1>
      <form method="post">
           {% csrf_token %}
       
            MINIMUM SALARY:<input type="number" size="10" name="salary"  style="font-size: 1rem;font-family: Comic Sans MS, cursive, sans-serif">
            MAXIMUM BOND YEARS:<input type="number" size="10" name="years"  style="font-size: 1rem;font-family: Comic Sans MS, cursive, sans-serif">
            <input type="submit" class="btn btn-primary" value="SEARCH">
        </form>
        <br>
      <table border="1px" style="text-align: center;border-collapse: collapse;background-color:rgb(96, 224, 214);"width=100%">
          <tr >
              <th style="font-size:1.5rem;color: #123027cc">Company </th>
              <th style="font-size:1.5rem;color: #123027cc">Designation</th>
                   <th style="font-size:1.5rem;color: #123027cc">Salary</th>
              <th style="font-size:1.5rem;color: #123027cc">Bond years</th>
              <th style="font-size:1.5rem;color:rgb(44, 143, 5)">Apply</th>
    
          </tr>
          {%  for i in y %}
          <tr>
              <td>{{ i.company_name }}</td>
          <td>{{ i.designation }}</td>
          <td>{{ i.salary }}</td>
          <td>{{ i.bond_years }}</td>
              <td><a href="http://127.0.0.1:8000/student/student_login/applyjob/{{ i.job_id }}/" target="popup" onclick="window.open('http://127.0.0.1:8000/student/student_login/applyjob/{{ i.job_id }}/','popup','width=600,height=600'); return false;" >APPLY</a></td>
          </tr>
          {% endfor %}
      </table> 


  </div>
  
</div>

{% endblock %}

campus/templates/campus/ccd.html
         {%extends "campus/base.html"%}
         
         {%block body_block%}
             <div class="container">
               <div class="row">
                 <div class="col-md-6 mx-auto text-center mb-5 section-heading">
                  
                   <br><br>
                   <h2>Modify details</h2>
                 </div>
               </div>
             </div>
             <div class="container">
               <div class="container">
                 <div class="jumbotron" style="background-color: lightgreen;">
                    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}


         <form method="post" >
            {% csrf_token %}
             <table>
                 <tr><td><label for="id_hr_name">HR Name:</label><input type="text" name="hr_name" value={{ x }} maxlength="10"  ></td></tr>

<tr><td><label for="id_phone_number">HR Phone number:</label><input type="text" name="hr_phn" value={{ y }} maxlength="10" minlength="10" ></td></tr>
                 <tr><th><label for="id_about">About:</label><textarea rows="10" cols="50" name="about"  maxlength="500" >{{ z}}</textarea></th></tr>

                 <tr>
                     <td><br><button type="submit" name="submit" class="btn btn-primary" value="Register" style="font-size: 1.5rem;" >MODIFY</button></td>
                </tr>
             </table>
         </form>
                 </div>
                   
               </div>
             </div>
             
             
         {%endblock%}

campus/templates/campus/compdisp.html
{% extends "campus/base.html" %}

{% block body_block %}
<div class="container">
    <div class="jumbotron">
            <form method="post">
            {% csrf_token %}
            <h1 style="font-size: 4rem;color: #bd2130;font-family: Comic Sans MS, cursive, sans-serif">ABOUT COMPANY</h1>
            <p>company name:<b>{{ post.company_name }}</b></p>
            <p>established year:<b>{{ post.est_year}}</b></p>
            <p>headquaters:<b>{{ post.headquaters}}</b></p>
            <p>about:<b>{{ post.about}}</b></p>
            <p>type:<b>{{ post.type}}</b></p>
            <p>email:<b>{{ post.email}}</b></p>
            <input type="submit" value="apply"  style="font-family: Comic Sans MS, cursive, sans-serif;font-size: 1.5rem">
        
    </form>
    </div>

</div>


{% endblock %}

campus/templates/campus/jobpos.html
<!DOCTYPE html>
{%extends "campus/base.html"%}

{%block body_block%}
          <div class="row">
              <div class="col-md-6 mx-auto text-center mb-5 section-heading">
               
                <br> <br>
                <h2>Post Vacancy</h2>
              </div>
            </div>
          <div class="container">
          <div class="jumbotron" style="background-color: lightgreen; ">
              <form method="post" >


                  {% if messages %}
                     <ul>
                         {% for message in messages %}
                         <li>{{ message }}</li>
                         {% endfor %}
                     </ul>
                 {% endif %}
         
         
                {% if form.errors %}
             {% for field in form %}
                 {% for error in field.errors %}
                     <div class="alert alert-danger">
                         <strong>{{ error|escape }}</strong>
                     </div>
                 {% endfor %}
             {% endfor %}
             {% for error in form.non_field_errors %}
                 <div class="alert alert-danger">
                     <strong>{{ error|escape }}</strong>
                 </div>
             {% endfor %}
         {% endif %}
         
         
         
             {% csrf_token %}
             <table>
             <tr><th></th><td><input type="hidden" name="company_name"  size="36" maxlength="30" required id="id_company_name" value={{ y }}  ></td></tr>
         <tr><th></th><td><input type="hidden" name="username" maxlength="30" required id="id_username" value={{ x }} > </td></tr><br>
         <tr><th><label for="id_job_id">Job id:</label></th><td><input type="text" name="job_id" maxlength="30" required id="id_job_id"><span class="helptext">*required</span></td></tr><br>
         <tr><th><label for="id_designation">Designation:</label></th><td><input type="text" name="designation" maxlength="30" required id="id_designation"><span class="helptext">*required</span></td></tr><br>
         <tr><th><label for="id_salary">Salary:</label></th><td><input type="number" name="salary" required id="id_salary"><span class="helptext">*required</span></td></tr><br>
         <tr><th><label for="id_bond_years">Bond years:</label></th><td><input type="number" name="bond_years" required id="id_bond_years"><span class="helptext">*required</span></td></tr><br>
         <tr><th><label for="id_information_technology">Information technology:</label></th><td><select name="information_technology" required id="id_information_technology">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_mech">Mech:</label></th><td><select name="mech" required id="id_mech">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_civil">Civil:</label></th><td><select name="civil" required id="id_civil">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_eee">Eee:</label></th><td><select name="eee" required id="id_eee">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_ece">Ece:</label></th><td><select name="ece" required id="id_ece">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_chemical">Chemical:</label></th><td><select name="chemical" required id="id_chemical">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         <tr><th><label for="id_cse">Cse:</label></th><td><select name="cse" required id="id_cse">
           <option value="" selected>---------</option>
         
           <option value="yes">yes</option>
         
           <option value="no">no</option>
         
         </select></td></tr>
         
             <br></table>
         <button type="submit" class="btn btn-danger"style="font-size: 1rem;">Submit</button>
         </form>
          </div>
          


      </div>
      


{%endblock%}
 

campus/templates/campus/usd.html
         <!DOCTYPE html>
         {%extends "campus/base.html"%}
         
         {%block body_block%}
             <div class="container-fluid">
               
                   <div class="row">
                       <div class="col-md-6 mx-auto text-center mb-5 section-heading">
                        
                         <br><br>
                         <h2>Modify Details</h2>
                       </div>
                     </div>
                   </div>
                   <div class="container">
                   <div class="jumbotron">
                      

                      {% if form.errors %}
                      {% for field in form %}
                          {% for error in field.errors %}
                              <div class="alert alert-danger">
                                  <strong>{{ error|escape }}</strong>
                              </div>
                          {% endfor %}
                      {% endfor %}
                      {% for error in form.non_field_errors %}
                          <div class="alert alert-danger">
                              <strong>{{ error|escape }}</strong>
                          </div>
                      {% endfor %}
                  {% endif %}
                  
                  
                           <form method="post" >
                              {% csrf_token %}
                               <table>
                                    <tr><th><label for="id_phone_number">Phone number:</label></th><td><input type="text" name="phone_number" maxlength="10" minlength="10" required id="id_phone_number"  value="{{ y }}"></td></tr>
                                    <tr><th><label>DOB</label></th><td><input type="date" maxlength="10" minlength="10" value="{{ db }}"></td></tr>
                                    <tr><th><label>Father's name</label></th><td><input type="text" maxlength="10" minlength="10" value="{{ fn }}"></td></tr>
                                    <tr><th><label>Mother's Name</label></th><td><input type="text" maxlength="10" minlength="10" value="{{ mn }}"></td></tr>
                                    <tr><th><label>Gender</label></th>
                                        <td>
                                        <input type="radio" name="gender" value="female" >female
                                        <input type="radio" name="gender" value="male" >male
                                        <input type="radio" name="gender" value="others" >others
                                        </td>
                                    </tr>
                                    <tr><th><label>Place</label></th><td><input type="text" maxlength="10" minlength="10" value="{{ p }}"></td></tr>
                                    <tr><th><label>Class 10 CGPA</label></th><td><input type="number" value="{{ c10 }}"></td></tr>
                                    <tr><th><label>Class 12 Percentage</label></th><td><input type="number" value="{{ c12 }}" ></td></tr>
                                    <tr><th><label>Internship</label></th><td><input type="text" value="yes/no" value="{{ i }}"></td></tr>
                                    <tr><th><label>Certification count</label></th><td><input type="number" maxlength="10" minlength="10" value="{{ cc }}"></td></tr>
                                    <tr><th><label>languages</label></th><td><input type="text" maxlength="10" minlength="10" value="{{ l }}"></td></tr>
                                    <tr><th><label>Email</label></th><td><input type="email" value="{{ e }}"></td></tr>
                                    <tr><th><label for="id_sop" value="{{ y }}">Sop:</label></th><td><textarea rows="10" cols="50" name="sop"  maxlength="500" required id="id_sop" value="{{ x }}"></textarea></td></tr>
                                    
                                   <tr>
                                      <td></td>
                                       <td><br><button type="submit" name="submit" value="Register" style="font-size: 1.5rem;font-family: Comic Sans MS, cursive, sans-serif"  class="btn btn-danger">MODIFY</button></td>
                                  </tr>

                               </table>
                           </form>
                       </div>
                   </div>
                   
         
         
               </div>
               
         
         
         {%endblock%}
          